#!/usr/bin/env python3
from pathlib import Path
from shutil import copy2


ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / 'output' / 'files' / 'figure_generation_sources' / 'fn' / 'FN_per_Fn.csv'
LEGACY_INPUT = ROOT / 'input' / 'figure_generation_sources' / 'fn' / 'FN_per_Fn.csv'

# Upstream generator provenance: FN/FN_per_fn_export.py
UPSTREAM_PATHS = [
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'outputs' / 'FN_Cost_Parameters' / 'FN_per_Fn.csv',
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'outputs' / 'FN_cost_parameters' / 'FN_per_Fn.csv',
]


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists():
        print(f'Exists: {OUT_PATH}')
        return 0

    for src in [LEGACY_INPUT, *UPSTREAM_PATHS]:
        if src.exists():
            copy2(src, OUT_PATH)
            print(f'Copied: {src}')
            print(f'Wrote: {OUT_PATH}')
            return 0

    raise FileNotFoundError(
        'Could not locate FN_per_Fn.csv. Expected legacy input or upstream outputs '
        '(generated by FN/FN_per_fn_export.py).'
    )


if __name__ == '__main__':
    raise SystemExit(main())
