#!/usr/bin/env python3
from pathlib import Path
from shutil import copy2


ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / 'output' / 'files' / 'figure_generation_sources' / 'fp' / 'fp_indirect_curve.csv'
LEGACY_INPUT = ROOT / 'input' / 'figure_generation_sources' / 'fp' / 'fp_indirect_curve.csv'

# Upstream generator provenance: run_paper_pipeline.py (build_fp_indirect_curve)
UPSTREAM_PATHS = [
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'paper_assets' / 'intermediate' / 'fp_indirect_curve.csv',
]


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists():
        print(f'Exists: {OUT_PATH}')
        return 0

    for src in [LEGACY_INPUT, *UPSTREAM_PATHS]:
        if src.exists():
            copy2(src, OUT_PATH)
            print(f'Copied: {src}')
            print(f'Wrote: {OUT_PATH}')
            return 0

    raise FileNotFoundError(
        'Could not locate fp_indirect_curve.csv. Expected legacy input or upstream outputs '
        '(generated by run_paper_pipeline.py / build_fp_indirect_curve).'
    )


if __name__ == '__main__':
    raise SystemExit(main())
