#!/usr/bin/env python3
from pathlib import Path
from shutil import copy2


ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / 'output' / 'files' / 'figure_generation_sources' / 'tstar' / 'tstar_by_scenario.csv'
LEGACY_INPUT = ROOT / 'input' / 'figure_generation_sources' / 'tstar' / 'tstar_by_scenario.csv'

# Upstream generator provenance: robustness/run_robustness.py
UPSTREAM_PATHS = [
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'robustness' / 'outputs_fw' / 'tstar_by_scenario.csv',
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'robustness' / 'outputs' / 'tstar_by_scenario.csv',
]


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists():
        print(f'Exists: {OUT_PATH}')
        return 0

    for src in [LEGACY_INPUT, *UPSTREAM_PATHS]:
        if src.exists():
            copy2(src, OUT_PATH)
            print(f'Copied: {src}')
            print(f'Wrote: {OUT_PATH}')
            return 0

    raise FileNotFoundError(
        'Could not locate tstar_by_scenario.csv. Expected legacy input or upstream outputs '
        '(generated by robustness/run_robustness.py).'
    )


if __name__ == '__main__':
    raise SystemExit(main())
