#!/usr/bin/env python3
from pathlib import Path
from shutil import copy2


ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / 'output' / 'files' / 'figure_generation_sources' / 'ecm' / 'all_ecm_costs_all_scenarios.csv'
LEGACY_INPUT = ROOT / 'input' / 'figure_generation_sources' / 'ecm' / 'all_ecm_costs_all_scenarios.csv'

# Upstream generator provenance: Final_combined/all_ecm_compute_by_category.py
# (Final_weighted and ALL_fp_fn variants also exist but produce different numbers.)
UPSTREAM_PATHS = [
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'Final_combined' / 'all_ecm_costs_all_scenarios.csv',
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'Final_weighted' / 'all_ecm_costs_all_scenarios.csv',
    ROOT.parents[1] / 'Coding - cost parameters ' / 'Cost parameters' / 'ALL_fp_fn' / 'all_ecm_costs_all_scenarios.csv',
]


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUT_PATH.exists():
        print(f'Exists: {OUT_PATH}')
        return 0

    for src in [LEGACY_INPUT, *UPSTREAM_PATHS]:
        if src.exists():
            copy2(src, OUT_PATH)
            print(f'Copied: {src}')
            print(f'Wrote: {OUT_PATH}')
            return 0

    raise FileNotFoundError(
        'Could not locate all_ecm_costs_all_scenarios.csv. Expected legacy input or upstream outputs '
        '(generated by Final_combined/all_ecm_compute_by_category.py in the matching branch).'
    )


if __name__ == '__main__':
    raise SystemExit(main())
